name: Process IssueComment events
on: 
  issue_comment:
    types:
      - created

permissions:
  id-token: write
  contents: read
  pull-requests: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  
  init:
    # Check if the comments come from pull request and starts with atlantis
    # exclude comments from issue.
    if: |
      contains(github.event.comment.html_url, '/pull') && 
      startsWith(github.event.comment.body, 'atlantis') 
    runs-on: ubuntu-latest
    steps:
      - id: 'get-branch'
        run: echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.get-branch.outputs.branch }}
    outputs:
      branch: ${{ steps.get-branch.outputs.branch }}
  
  deploy-in-sandbox:
    if: startsWith(needs.init.outputs.branch, 'sandbox/')
    uses: ./.github/workflows/deploy.yml
    needs: init
    with:
      execution_environment: sandbox
      branch: ${{ needs.init.outputs.branch }}
    secrets: inherit

  deploy-in-dev:
    if: startsWith(needs.init.outputs.branch, 'dev/')
    uses: ./.github/workflows/deploy.yml
    needs: init
    with:
      execution_environment: dev
      branch: ${{ needs.init.outputs.branch }}
    secrets: inherit

  deploy-in-pre:
    if: startsWith(needs.init.outputs.branch, 'pre/')
    uses: ./.github/workflows/deploy.yml
    needs: init
    with:
      execution_environment: pre
      branch: ${{ needs.init.outputs.branch }}
    secrets: inherit
  
  deploy-in-prod:
    if: startsWith(needs.init.outputs.branch, 'prod/')
    uses: ./.github/workflows/deploy.yml
    needs: init
    with:
      execution_environment: prod
      branch: ${{ needs.init.outputs.branch }}
    secrets: inherit
