name: Process PullRequest events
on: 
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
        - 'docs/**'
        - '*.md'
    branches:
    # restrict actions on pull requests to only 
    # run when created against the main branch
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  deploy-in-sandbox:
    if: |
      !github.event.pull_request.draft &&
      startsWith(github.head_ref, 'sandbox/')
    uses: ./.github/workflows/deploy.yml
    with:
      execution_environment: sandbox
      branch: ${{ github.head_ref }}
    secrets: inherit

  deploy-in-dev:
    if: |
      !github.event.pull_request.draft &&
      startsWith(github.head_ref, 'dev/')
    uses: ./.github/workflows/deploy.yml
    with:
      execution_environment: dev
      branch: ${{ github.head_ref }}
    secrets: inherit

  deploy-in-pre:
    if: |
      !github.event.pull_request.draft &&
      startsWith(github.head_ref, 'pre/')
    uses: ./.github/workflows/deploy.yml
    with:
      execution_environment: pre
      branch: ${{ github.head_ref }}
    secrets: inherit
  
  deploy-in-prod:
    if: |
      !github.event.pull_request.draft &&
      startsWith(github.head_ref, 'prod/')
    uses: ./.github/workflows/deploy.yml
    with:
      execution_environment: prod
      branch: ${{ github.head_ref }}
    secrets: inherit
