name: Test
on: 
  pull_request:
  push:
jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Markdown
        run: echo "The current environment is ${{ github.environment }}"

      # Checks to see if any files in the PR match one of the listed file types.
      # We can use this filter to decide whether or not to run linters or tests.
      # You can check if a file with a listed file type is in the PR by doing:
      # if: ${{ steps.filter.outputs.md == 'true' }}
      # This will return true if there's a markdown file that was changed
      # in the PR.
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            sandbox:
              - 'live/sandbox/**'
            dev:
              - 'live/dev/**'
